export {
  ensureEmsSeeded,
  listEmsTemplates,
  getEmsTemplate,
  upsertEmsTemplate,
  duplicateEmsTemplate,
  softDeleteEmsTemplate,
  listEmsCategories,
  createEmsCategory,
  deleteEmsCategory,
  listEmsSenders,
  createEmsSender,
  updateEmsSender,
  deleteEmsSender,
  listEmsVariables,
  createEmsVariable,
  listEmsAutomations,
  upsertEmsAutomation,
  listEmsQueue,
  retryEmsQueueItem,
  cancelEmsQueueItem,
  enqueueAndSend,
  sendTestEmsTemplate,
  emitEmailEvent,
  getEmsAnalytics,
  getEmsSettingsExtended,
  updateEmsSettingsExtended,
} from "./service"
