-- Ops suite: SMTP fields, admin TOTP, twoFactorRequired
ALTER TABLE "EmailSetting" ADD COLUMN IF NOT EXISTS "smtpHost" TEXT;
ALTER TABLE "EmailSetting" ADD COLUMN IF NOT EXISTS "smtpPort" INTEGER NOT NULL DEFAULT 587;
ALTER TABLE "EmailSetting" ADD COLUMN IF NOT EXISTS "smtpUser" TEXT;
ALTER TABLE "EmailSetting" ADD COLUMN IF NOT EXISTS "smtpPassword" TEXT;
ALTER TABLE "EmailSetting" ADD COLUMN IF NOT EXISTS "smtpSecure" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "AuthenticationSetting" ADD COLUMN IF NOT EXISTS "twoFactorRequired" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpSecret" TEXT;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
