import type { DashboardHomeData } from "../types/types";

/** Placeholder dashboard home payload — real data arrives with each source MES. */
export const SEEDED_DASHBOARD_HOME: DashboardHomeData = {
  stats: [
    { id: "articles", label: "Articles", value: "128", trend: "+13% from last 7 days" },
    { id: "images", label: "Images", value: "459", trend: "+8% from last 7 days" },
    { id: "videos", label: "Videos", value: "78", trend: "+5% from last 7 days" },
    { id: "guides", label: "Learn Guides", value: "52", trend: "+11% from last 7 days" },
    { id: "visitors", label: "Total Visitors", value: "18,342", trend: "+20% from last 7 days" },
    { id: "da", label: "Domain Authority", value: "92", trend: "+2 from last month" },
  ],
  quickAccess: [
    { id: "qa1", label: "Create Article", href: "/dashboard/articles/new", description: "Start a new draft" },
    { id: "qa2", label: "Create Guide", href: "/dashboard/guides/new", description: "New learning path" },
    { id: "qa3", label: "Add Category", href: "/dashboard/categories/new", description: "Organize content" },
    { id: "qa4", label: "Add Topic", href: "/dashboard/topics/new", description: "Topic graph" },
    { id: "qa5", label: "Upload Media", href: "/dashboard/media/upload", description: "Images & assets" },
    { id: "qa6", label: "Create Page", href: "/dashboard/pages", description: "Static page" },
    { id: "qa7", label: "Navbar Manager", href: "/dashboard/navigation", description: "Site navigation" },
    { id: "qa8", label: "Homepage Builder", href: "/dashboard/homepage", description: "Public homepage" },
    { id: "qa9", label: "AI Image Generator", href: "/dashboard/ai-studio/image", description: "DALL·E / AI images" },
    { id: "qa10", label: "AI Video Generator", href: "/dashboard/ai-studio/video", description: "Short-form video" },
    { id: "qa11", label: "AI Article Draft", href: "/dashboard/ai-studio/article", description: "Claude-assisted" },
    { id: "qa12", label: "View Analytics", href: "/dashboard/analytics", description: "Traffic & SEO" },
  ],
  activity: [
    { id: "a1", title: "AI article published: How AI Agents Work", meta: "Articles", time: "2h ago" },
    { id: "a2", title: "Featured image generated for RAG guide", meta: "AI Studio", time: "4h ago" },
    { id: "a3", title: "Homepage published with new hero", meta: "Homepage", time: "Yesterday" },
    { id: "a4", title: "New subscriber joined newsletter", meta: "Growth", time: "Yesterday" },
  ],
  recentArticles: [
    {
      id: "r1",
      title: "ChatGPT Complete Guide: Beginner to Power User",
      status: "published",
      author: "Claude AI",
      seoScore: 92,
      views: "2.4K",
      date: "Jul 15",
    },
    {
      id: "r2",
      title: "Building AI Agents: Step-by-Step Guide",
      status: "published",
      author: "Editorial",
      seoScore: 88,
      views: "1.8K",
      date: "Jul 14",
    },
    {
      id: "r3",
      title: "Gemini vs ChatGPT: 2026 Comparison",
      status: "scheduled",
      author: "Claude AI",
      seoScore: 76,
      views: "—",
      date: "Jul 18",
    },
    {
      id: "r4",
      title: "Vector Databases Compared",
      status: "draft",
      author: "Editorial",
      seoScore: 61,
      views: "0",
      date: "Jul 16",
    },
  ],
  contentOverview: [
    { id: "c1", label: "Articles", value: 128, color: "#8B5CF6" },
    { id: "c2", label: "Guides", value: 52, color: "#6366F1" },
    { id: "c3", label: "Pages", value: 24, color: "#22D3EE" },
    { id: "c4", label: "Videos", value: 78, color: "#A855F7" },
    { id: "c5", label: "Images", value: 459, color: "#EC4899" },
  ],
  topCategories: [
    { id: "tc1", name: "Artificial Intelligence", count: 42 },
    { id: "tc2", name: "Web Development", count: 31 },
    { id: "tc3", name: "Machine Learning", count: 28 },
    { id: "tc4", name: "AI Tools", count: 22 },
    { id: "tc5", name: "Data Science", count: 18 },
  ],
  analytics: [
    { id: "an1", label: "Visitors", value: "4.8K", delta: "+12%" },
    { id: "an2", label: "Page Views", value: "21.3K", delta: "+8%" },
    { id: "an3", label: "Avg Read Time", value: "3m 12s", delta: "+4%" },
    { id: "an4", label: "Bounce Rate", value: "41%", delta: "-3%" },
    { id: "an5", label: "SEO Score", value: "78", delta: "+2" },
    { id: "an6", label: "New Subscribers", value: "126", delta: "+19%" },
  ],
  analyticsCharts: [
    {
      id: "an1",
      label: "Visitors",
      value: "4.8K",
      delta: "+12%",
      points: [
        { label: "Mon", value: 320 },
        { label: "Tue", value: 410 },
        { label: "Wed", value: 380 },
        { label: "Thu", value: 520 },
        { label: "Fri", value: 490 },
        { label: "Sat", value: 610 },
        { label: "Sun", value: 680 },
      ],
    },
    {
      id: "an2",
      label: "Page Views",
      value: "21.3K",
      delta: "+8%",
      points: [
        { label: "Mon", value: 2100 },
        { label: "Tue", value: 2450 },
        { label: "Wed", value: 2280 },
        { label: "Thu", value: 2900 },
        { label: "Fri", value: 3100 },
        { label: "Sat", value: 3400 },
        { label: "Sun", value: 3650 },
      ],
    },
    {
      id: "an3",
      label: "Avg Read Time",
      value: "3m 12s",
      delta: "+4%",
      points: [
        { label: "Mon", value: 168 },
        { label: "Tue", value: 172 },
        { label: "Wed", value: 180 },
        { label: "Thu", value: 185 },
        { label: "Fri", value: 190 },
        { label: "Sat", value: 192 },
        { label: "Sun", value: 195 },
      ],
    },
    {
      id: "an4",
      label: "Bounce Rate",
      value: "41%",
      delta: "-3%",
      points: [
        { label: "Mon", value: 44 },
        { label: "Tue", value: 43 },
        { label: "Wed", value: 42 },
        { label: "Thu", value: 41 },
        { label: "Fri", value: 40 },
        { label: "Sat", value: 39 },
        { label: "Sun", value: 38 },
      ],
    },
    {
      id: "an5",
      label: "SEO Score",
      value: "78",
      delta: "+2",
      points: [
        { label: "Mon", value: 74 },
        { label: "Tue", value: 75 },
        { label: "Wed", value: 76 },
        { label: "Thu", value: 77 },
        { label: "Fri", value: 78 },
        { label: "Sat", value: 79 },
        { label: "Sun", value: 80 },
      ],
    },
    {
      id: "an6",
      label: "New Subscribers",
      value: "126",
      delta: "+19%",
      points: [
        { label: "Mon", value: 12 },
        { label: "Tue", value: 15 },
        { label: "Wed", value: 14 },
        { label: "Thu", value: 18 },
        { label: "Fri", value: 22 },
        { label: "Sat", value: 24 },
        { label: "Sun", value: 21 },
      ],
    },
  ],
  workflow: [
    { id: "w1", label: "Topic", status: "done" },
    { id: "w2", label: "Claude AI", status: "done" },
    { id: "w3", label: "Generate Media", status: "current" },
    { id: "w4", label: "SEO Optimization", status: "upcoming" },
    { id: "w5", label: "Review", status: "upcoming" },
    { id: "w6", label: "Schedule/Publish", status: "upcoming" },
  ],
  aiStatus: [
    {
      id: "claude",
      name: "Claude (Anthropic)",
      connected: false,
      detail: "Adapter stub — configure in Integrations",
    },
    {
      id: "openai",
      name: "OpenAI",
      connected: false,
      detail: "Not configured",
    },
    {
      id: "gemini",
      name: "Gemini (Google)",
      connected: false,
      detail: "Adapter stub",
    },
    {
      id: "grok",
      name: "Grok (xAI)",
      connected: false,
      detail: "Adapter stub",
    },
    {
      id: "dalle",
      name: "DALL·E",
      connected: false,
      detail: "Via OpenAI",
    },
  ],
  system: [
    { id: "s1", label: "Storage Usage", value: "26%", detail: "128.45 GB / 500 GB" },
    { id: "s2", label: "Bandwidth Usage", value: "24%", detail: "245.8 GB / 1 TB" },
    { id: "s3", label: "AI Credits Remaining", value: "78%", detail: "78,432 / 100,000" },
  ],
};
