import type { HomepageContent } from "../types/types";

/**
 * Seeded homepage payload (MES-005).
 * MES-013 Homepage CMS will persist/override this shape via Settings/Content.
 */
export const SEEDED_HOMEPAGE_CONTENT: HomepageContent = {
  sections: [
    { id: "hero", visible: true, order: 1 },
    { id: "ask", visible: false, order: 2 },
    { id: "stats", visible: false, order: 3 },
    { id: "articles", visible: true, order: 4 },
    { id: "categories", visible: true, order: 5 },
    { id: "why", visible: true, order: 6 },
    { id: "paths", visible: true, order: 7 },
    { id: "tools", visible: true, order: 8 },
    { id: "testimonials", visible: true, order: 9 },
    { id: "newsletter", visible: true, order: 10 },
    { id: "faq", visible: true, order: 11 },
    { id: "finalCta", visible: true, order: 12 },
  ],
  hero: {
    brand: "Mendanize",
    eyebrow: "Stay Ahead with AI",
    headline: "Learn. Explore.",
    headlineLead: "Master",
    headlineAccent: "AI.",
    description:
      "Your ultimate resource for AI tools, tutorials, and insights. Learn from experts, discover cutting-edge tools, and stay ahead in the AI revolution.",
    primaryCta: { label: "Explore Latest Articles", href: "/articles" },
    secondaryCta: { label: "Browse All Tools", href: "/ai-tools" },
    trustLine: "",
  },
  ask: {
    title: "Ask Mendanize",
    description: "Ask anything about AI, tools, and learning paths.",
    placeholder: "Ask Mendanize AI anything about AI",
    suggestions: [
      "What is RAG?",
      "How do AI agents work?",
      "Claude vs GPT-4o",
      "Best AI tools for developers",
    ],
  },
  stats: [
    { id: "articles", label: "Articles", value: "10K+", icon: "articles" },
    { id: "tools", label: "AI Tools", value: "500+", icon: "tools" },
    { id: "learners", label: "Learners", value: "50K+", icon: "learners" },
    { id: "subscribers", label: "Subscribers", value: "100K+", icon: "subscribers" },
    { id: "content", label: "Weekly New Content", value: "Fresh", icon: "content" },
    { id: "hub", label: "AI-Powered Learning Hub", value: "Live", icon: "hub" },
  ],
  categories: [
    { id: "ai", title: "Artificial Intelligence", href: "/categories", icon: "sparkles", iconColor: "#8B5CF6" },
    { id: "ml", title: "Machine Learning", href: "/categories", icon: "brain", iconColor: "#6366F1" },
    { id: "dl", title: "Deep Learning", href: "/categories", icon: "layers", iconColor: "#22D3EE" },
    { id: "ds", title: "Data Science", href: "/categories", icon: "chart", iconColor: "#10B981" },
    { id: "prog", title: "Programming", href: "/categories", icon: "terminal", iconColor: "#F59E0B" },
    { id: "web", title: "Web Development", href: "/categories", icon: "code", iconColor: "#3B82F6" },
    { id: "mobile", title: "Mobile Dev", href: "/categories", icon: "mobile", iconColor: "#EC4899" },
    { id: "cloud", title: "Cloud Computing", href: "/categories", icon: "server", iconColor: "#A855F7" },
    { id: "security", title: "Cybersecurity", href: "/categories", icon: "shield", iconColor: "#EF4444" },
    { id: "devops", title: "DevOps", href: "/categories", icon: "rocket", iconColor: "#14B8A6" },
    { id: "design", title: "UX/UI Design", href: "/categories", icon: "palette", iconColor: "#F472B6" },
    { id: "db", title: "Databases", href: "/categories", icon: "database", iconColor: "#818CF8" },
    { id: "blockchain", title: "Blockchain", href: "/categories", icon: "lock", iconColor: "#FBBF24" },
    { id: "iot", title: "IoT", href: "/categories", icon: "globe", iconColor: "#34D399" },
    { id: "agents", title: "AI Agents", href: "/categories", icon: "bot", iconColor: "#C084FC" },
    { id: "nlp", title: "NLP", href: "/categories", icon: "sparkles", iconColor: "#60A5FA" },
    { id: "cv", title: "Computer Vision", href: "/categories", icon: "brain", iconColor: "#2DD4BF" },
    { id: "llm", title: "LLMs", href: "/categories", icon: "layers", iconColor: "#FB7185" },
    { id: "prompt", title: "Prompt Engineering", href: "/categories", icon: "terminal", iconColor: "#A78BFA" },
    { id: "auto", title: "Automation", href: "/categories", icon: "rocket", iconColor: "#4ADE80" },
    { id: "analytics", title: "Analytics", href: "/categories", icon: "chart", iconColor: "#38BDF8" },
    { id: "startup", title: "Startups", href: "/categories", icon: "rocket", iconColor: "#F97316" },
    { id: "product", title: "Product", href: "/categories", icon: "palette", iconColor: "#E879F9" },
    { id: "career", title: "Career", href: "/categories", icon: "globe", iconColor: "#86EFAC" },
  ],
  paths: [
    {
      id: "ai-foundations",
      title: "AI Foundations",
      description: "From basics to building with language models.",
      href: "/guides",
      difficulty: "Beginner",
      duration: "4 hours",
      lessons: 8,
    },
    {
      id: "fullstack",
      title: "Full-Stack Starter",
      description: "Ship a reliable app with modern Next.js patterns.",
      href: "/guides",
      difficulty: "Intermediate",
      duration: "6 hours",
      lessons: 12,
    },
    {
      id: "seo-content",
      title: "SEO for Educators",
      description: "Structure learning content that ranks and teaches.",
      href: "/guides",
      difficulty: "Beginner",
      duration: "3 hours",
      lessons: 7,
    },
  ],
  articles: [
    {
      id: "a1",
      title: "ChatGPT Complete Guide: From Beginner to Power User",
      description: "Master prompts, plugins, and advanced workflows for daily productivity.",
      href: "/articles",
      category: "AI TOOLS",
      readingTime: "12 min",
      author: "Editorial",
      date: "Jul 15, 2026",
    },
    {
      id: "a2",
      title: "Google Gemini vs ChatGPT: Which AI Wins in 2026?",
      description: "A head-to-head comparison of capabilities, pricing, and real-world use cases.",
      href: "/articles",
      category: "AI NEWS",
      readingTime: "8 min",
      author: "Editorial",
      date: "Jul 14, 2026",
    },
    {
      id: "a3",
      title: "Building AI Agents: A Practical Step-by-Step Guide",
      description: "Learn how to design, build, and deploy autonomous AI agents.",
      href: "/articles",
      category: "TUTORIAL",
      readingTime: "15 min",
      author: "Editorial",
      date: "Jul 12, 2026",
    },
    {
      id: "a4",
      title: "50 Must-Have AI Tools for Developers in 2026",
      description: "The definitive toolkit for coding, testing, and shipping faster with AI.",
      href: "/articles",
      category: "AI TOOLS",
      readingTime: "10 min",
      author: "Editorial",
      date: "Jul 10, 2026",
    },
  ],
  latestArticles: [
    {
      id: "l1",
      title: "Understanding RAG: Retrieval-Augmented Generation Explained",
      description: "",
      href: "/articles",
      category: "AI",
      readingTime: "7 min",
      author: "Editorial",
      date: "Jul 16, 2026",
    },
    {
      id: "l2",
      title: "Claude 4 vs GPT-4o: Benchmarks and Real-World Tests",
      description: "",
      href: "/articles",
      category: "AI",
      readingTime: "9 min",
      author: "Editorial",
      date: "Jul 15, 2026",
    },
    {
      id: "l3",
      title: "Vector Databases Compared: Pinecone, Weaviate, and Chroma",
      description: "",
      href: "/articles",
      category: "Tools",
      readingTime: "11 min",
      author: "Editorial",
      date: "Jul 14, 2026",
    },
    {
      id: "l4",
      title: "Fine-Tuning LLMs: When and How to Do It Right",
      description: "",
      href: "/articles",
      category: "Tutorial",
      readingTime: "13 min",
      author: "Editorial",
      date: "Jul 13, 2026",
    },
    {
      id: "l5",
      title: "The State of Open Source AI Models in 2026",
      description: "",
      href: "/articles",
      category: "AI News",
      readingTime: "6 min",
      author: "Editorial",
      date: "Jul 12, 2026",
    },
    {
      id: "l6",
      title: "Prompt Engineering Patterns That Actually Stick",
      description: "",
      href: "/articles",
      category: "Guides",
      readingTime: "8 min",
      author: "Editorial",
      date: "Jul 11, 2026",
    },
    {
      id: "l7",
      title: "Building Reliable AI Toolchains for Teams",
      description: "",
      href: "/articles",
      category: "Tools",
      readingTime: "10 min",
      author: "Editorial",
      date: "Jul 10, 2026",
    },
  ],
  tools: [
    {
      id: "t1",
      name: "Claude",
      description: "Strong reasoning for research and technical writing.",
      href: "/ai-tools",
      category: "LLM",
      rating: "4.8",
    },
    {
      id: "t2",
      name: "Cursor",
      description: "AI-assisted coding in a modern editor workflow.",
      href: "/ai-tools",
      category: "Devtools",
      rating: "4.7",
    },
    {
      id: "t3",
      name: "Perplexity",
      description: "Research with citations for faster learning loops.",
      href: "/ai-tools",
      category: "Research",
      rating: "4.6",
    },
  ],
  why: [
    {
      id: "insights",
      title: "AI-Powered Insights",
      description:
        "Get personalized learning recommendations powered by AI.",
      icon: "insights",
    },
    {
      id: "tutorials",
      title: "Step-by-Step Tutorials",
      description:
        "Clear, practical guides from beginner to advanced.",
      icon: "tutorials",
    },
    {
      id: "community",
      title: "Community Focused",
      description:
        "Learn alongside thousands of AI enthusiasts worldwide.",
      icon: "community",
    },
    {
      id: "updated",
      title: "Always Updated",
      description:
        "Fresh content every week as AI evolves rapidly.",
      icon: "updated",
    },
    {
      id: "skills",
      title: "Real Skills",
      description:
        "Apply what you learn with hands-on projects.",
      icon: "skills",
    },
    {
      id: "ask",
      title: "Ask Mendanize AI",
      description:
        "Get instant answers to your learning questions.",
      icon: "ask",
    },
  ],
  testimonials: [
    {
      id: "tm1",
      quote:
        "Finally a learning site that explains AI without talking down or glossing over.",
      name: "Jordan Lee",
      role: "Software engineer",
    },
    {
      id: "tm2",
      quote:
        "The guided paths helped me move from tutorials to shipping with confidence.",
      name: "Priya Shah",
      role: "Product designer",
    },
    {
      id: "tm3",
      quote: "Clean, fast, and focused on understanding — not hype.",
      name: "Marcus Chen",
      role: "Founder",
    },
  ],
  newsletter: {
    headline: "Stay Updated",
    description: "Get the latest AI news, tutorials, and tool reviews delivered weekly.",
    privacy: "No spam. Unsubscribe anytime.",
    placeholder: "Enter your email",
    ctaLabel: "Subscribe",
    socialProof: "Join 50,000+ AI enthusiasts",
  },
  faq: [
    {
      id: "f1",
      question: "Is Mendanize free to use?",
      answer:
        "The teaching frontend is public. Premium assistant and workspace features arrive with billing later.",
    },
    {
      id: "f2",
      question: "Who is Mendanize for?",
      answer:
        "Students, developers, founders, and professionals who want clearer technology education.",
    },
    {
      id: "f3",
      question: "Does Ask Mendanize answer questions now?",
      answer:
        "The homepage widget is interface-only in this phase. Live AI wiring lands with the Ask MES later.",
    },
    {
      id: "f4",
      question: "Can admins edit homepage sections?",
      answer:
        "Yes — section order, visibility, and copy are designed for Homepage CMS (MES-013).",
    },
  ],
  finalCta: {
    headline: "Ready to get more from Mendanize?",
    description:
      "Create a free account to unlock guided learning paths, AI tools, saved content, and the full Mendanize product experience.",
    primaryCta: { label: "Create account", href: "/sign-up" },
    secondaryCta: { label: "Explore guides", href: "/guides" },
  },
};
